include: package:flutter_lints/flutter.yaml
analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart]
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_single_quotes: true # Uncomment to enable the `prefer_single_quotes` rule

