name: cloud_photo_gallery
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.4
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  dio_cache_interceptor: ^3.2.7
  dio_cache_interceptor_hive_store: ^3.1.1
  dio_logger: ^4.0.8+8
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_downloader: ^1.8.0+1
  flutter_local_notifications: ^9.6.0
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  infinite_scroll_pagination: ^3.2.0
  package_info_plus: ^1.4.2
  staggered_grid_view_flutter: ^0.0.4

dev_dependencies:
  build_runner: ^2.1.11
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  lint: ^1.8.2

flutter_app_name:
  name: "Cloud Photo Gallery"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/launcher_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
